### ISSUE TITLE
No autoload for traad-install-server, had to require it

### ISSUE THREAD

**Issue by vindarel** [abingham/emacs-traad#3]
Hi, 
this is a great package !
A detail is that right after installation I couldn't find traad-install-server, as says the readme, even if it's an interactive function, because it is not \#autoloaded.

There is no "add argument" function ?

**Comment by abingham** [comment]
Try out the [autoload-install-function](https://github.com/abingham/emacs-traad/tree/autoload-install-function) branch. If that works for you then I'll merge it in.

**Comment by abingham** [comment]
> There is no "add argument" function ?

I think that must have been added to rope since I last worked on traad. To add support for this we'd need to:

1. Add support for it to [traad](https://github.com/abingham/traad)
2. Then add support to this project

I don't think either would be too difficult, but I really don't have time for it right now. If you want to take a try at adding it, I'll be more than happy to help out if necessary, and of course I'd be delighted to have to additions.

**Comment by vindarel** [comment]
that works for me thanks !

I'll have a look and open another issue for discussion if necessary.

**Comment by abingham** [comment]
Great! I'll merge in the PR and close this out. Thanks for taking the time to report this.

**Comment by abingham** [comment]
Fixed in de76278e77d26ab8c400c03cef7bc3326be1e257

**Comment by vindarel** [comment]
btw I can't find a mention of adding a method parameter on [rope overview](https://github.com/python-rope/rope/blob/master/docs/overview.rst). Might as well ask.

**Comment by abingham** [comment]
> I can't find a mention of adding a method parameter

[This `ArgumentAdder` class](https://github.com/python-rope/rope/blob/master/rope/refactor/change_signature.py#L218) sounds like it should do the trick. I think they just haven't updated their docs yet. If you looks in [`traad.rope.change_signature`](https://github.com/abingham/traad/blob/master/traad/rope/change_signature.py) I think it should be pretty clear how to add support to the traad core.
