### ISSUE TITLE
python-environment.el or virtualenvwrapper.el adopted ?

### ISSUE THREAD

**Issue by hekinami** [abingham/emacs-traad#6]
In the wiki, it was said that python-environment.el was used. But if we look into the source code, I found actually virtualenvwrapper.el was used if we run traad-install-server. It was really confusing when I tried to install it with python3.  Which should be the future?

**Comment by abingham** [comment]
Sorry for the confusion! I failed to update the wiki when I switched over to virtualenvwrapper.el. 

traad.el uses virtualenvwrapper.el, and I've updated the wiki to reflect that. Hopefully this helps clear things up.

If everything looks ok to you now, please close this issue. Thanks for taking the time to report this!

**Comment by hekinami** [comment]
Thank you for your response. Then how could we use traad with python 3? I found if  we run traad-install-server virtualenvwrapper.el only use virtualenv (which in most case is pointing to python 2) to create the virtual env, could you tell me how could we create a python 3 env for traad?

**Comment by abingham** [comment]
It should work if you do this. First, create a virtualenv that uses
python3. You can use any approach you want for this: virtualenvwrapper.el,
python-environment.el, or create it outside of emacs.

Then set traad-environment-name to the environment you just created. Now if
you call traad-install-server it should use the python3 environment.

I'm not at my computer so i can't test it, but let me know if you have any
problems. This system could probably be better, but I haven't had much time
to put into it.

On Sun, Mar 19, 2017, 11:35 Zou Bibo <notifications@github.com> wrote:

Thank you for your response. Then how could we use traad with python 3? I
found if we run traad-install-server virtualenvwrapper.el only use
virtualenv (which in most case is pointing to python 2) to create the
virtual env, could you tell me how could we create a python 3 env for traad?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/abingham/emacs-traad/issues/6#issuecomment-287607472>,
or mute the thread

**Comment by hekinami** [comment]
Thanks, this works.

To be honest, I think python-environment.el might be more convenient and configurable. Yet I believe you have your reason to switch to  virtualenvwrapper.el.

Anyway let's close this issue.

**Comment by abingham** [comment]
I'm glad it works.

I'd be happy to hear arguments in favor of python-environment.el. From what
I can see, the use of virtualenvwrapper.el vs. python-environment.el makes
no difference to users of emacs-traad.el except for the dependency itself,
but maybe I've missed something. So if there's something that
python-enviroment.el would improve, I would certainly like to know.

I don't remember the fundamental reason that I chose virtualenvwrapper.el
over python-environment.el. I do see, though, that python-environment.el
hasn't been updated in over 2 years. I've had problems with tkf abandoning
projects in the past, so I might have decided that it wasn't worth the
risk. In any event, I think emacs-traad would probably be fine with either
technology.
